config/routes.rb
QaHub::Application.routes.draw do
  devise_for :users, path_names: { sign_up: 'register', sign_in: 'sign-in', sign_out: 'sign-out' }
  
  root to: 'static_pages#home'
  
  resources :releases
  
  resources :checklists do
  	get 'toggle_tool', on: :member
  	get 'toggle_item', on: :member
  	get 'toggle_applicable', on: :member
  end
  
  resources :release_items
  
  resources :comments
end

app/models/release_item.rb
class ReleaseItem < ActiveRecord::Base
  attr_accessible :release_id, :item_type, :source, :source_reference, :title, :is_config_change, :is_data_change, :affected_product, :level_of_comfort, :level_of_risk, :comments, :modified_by
  
  belongs_to :release, touch: true
  
  validates_presence_of :title, :item_type, :source, :affected_product, :level_of_comfort, :level_of_risk, :comments, :modified_by
  validates_inclusion_of :is_data_change, :is_config_change, in: [true, false]
  validates_length_of :title, maximum: 500
  validates_length_of :comments, maximum: 1000
end

app/controllers/release_items_controller.rb
class ReleaseItemsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]
  
  def index
    @release = Release.find(params[:id])
    @release_items = ReleaseItem.find(:all, select: "release_items.*, users.email, users.name", joins: "LEFT JOIN users ON users.email = release_items.modified_by", conditions: ["release_items.release_id = ?", params[:id]], order: "release_items.id ASC")
    @release_items_levels_averages = ReleaseItem.find(:all, select: "ROUND(AVG(level_of_risk)) AS risk_level_average, ROUND(AVG(level_of_comfort)) AS comfort_level_average", conditions: ["release_id = ?", params[:id]]).first
    @items_data, @items_general, @items_patch, @items_project, @items_upgrade = [], [], [], [], []
    @release_items.each do |item|
      @items_data << item if item.item_type == 'Data'
      @items_general << item if item.item_type == 'General'
      @items_patch << item if item.item_type == 'Patch'
      @items_project << item if item.item_type == 'Project'
      @items_upgrade << item if item.item_type == 'Upgrade'
    end
  end
  
  def new
    @release_item = ReleaseItem.new
    @affected_browsers_data = AffectedBrowsersData.find(:all, conditions: ["active = ?", true], order: "priority ASC")
    @affected_designs_data = AffectedDesignsData.find(:all, conditions: ["active = ?", true], order: "category ASC, label ASC")
    @designs_acura, @designs_chevrolet, @designs_general, @designs_gsm, @designs_ford, @designs_mazda, @designs_scion, @designs_tools = [], [], [], [], [], [], [], []
    @affected_designs_data.each do |design|
      @designs_acura << design if design.category == 'Acura'
      @designs_chevrolet << design if design.category == 'Chevrolet'
      @designs_general << design if design.category == 'General'
      @designs_gsm << design if design.category == 'GSM'
      @designs_ford << design if design.category == 'Ford'
      @designs_mazda << design if design.category == 'Mazda'
      @designs_scion << design if design.category == 'Scion'
      @designs_tools << design if design.category == 'Tools'
    end
  end
  
  def create
    @release_item = ReleaseItem.new(params[:release_item])
    affected_browsers = params[:affected_browsers]
    affected_designs = params[:affected_designs]
    if affected_browsers
	    @release_item.affected_browsers = affected_browsers.join(", ")
	  end
	  if affected_designs
      @release_item.affected_designs = affected_designs.join(", ")
    end
    if @release_item.save
      flash[:success] = "\"#{@release_item.title}\" has been created as a new release item."
      redirect_to release_items_path(id: @release_item.release_id)
    else
      @affected_browsers_data = AffectedBrowsersData.find(:all, conditions: ["active = ?", true], order: "label ASC")
      @affected_designs_data = AffectedDesignsData.find(:all, conditions: ["active = ?", true], order: "label ASC")
      render 'new'
    end
  end
  
  def edit
    @release_item = ReleaseItem.find(params[:id])
    @affected_browsers_data = AffectedBrowsersData.find(:all, conditions: ["active = ?", true], order: "priority ASC")
    @affected_designs_data = AffectedDesignsData.find(:all, conditions: ["active = ?", true], order: "category ASC, label ASC")
    @designs_acura, @designs_asbury, @designs_bmw, @designs_dealer, @designs_facebook, @designs_ford, @designs_gsm, @designs_infiniti, @designs_lincoln, @designs_mobile, @designs_nissan, @designs_scion, @designs_tools, @designs_general = [], [], [], [], [], [], [], [], [], [], [], [], [], [], []
    @affected_designs_data.each do |design|
      @designs_acura << design if design.category == 'Acura'
      @designs_asbury << design if design.category == 'Asbury'
      @designs_bmw << design if design.category == 'BMW'
      @designs_dealer << design if design.category == 'Dealer'
      @designs_facebook << design if design.category == 'Facebook'
      @designs_ford << design if design.category == 'Ford'
      @designs_gsm << design if design.category == 'GSM'
      @designs_infiniti << design if design.category == 'Infiniti'
      @designs_lincoln << design if design.category == 'Lincoln'
      @designs_mobile << design if design.category == 'Mobile'
      @designs_nissan << design if design.category == 'Nissan'
      @designs_scion << design if design.category == 'Scion'
      @designs_tools << design if design.category == 'Tools'
      @designs_general << design if design.category == 'General'
    end
  end
  
  def update
    @release_item = ReleaseItem.find(params[:id])
    affected_browsers = params[:affected_browsers]
    affected_designs = params[:affected_designs]
    if affected_browsers
	    @release_item.affected_browsers = affected_browsers.join(", ")
	  end
	  if affected_designs
      @release_item.affected_designs = affected_designs.join(", ")
    end
    if @release_item.update_attributes(params[:release_item])
      redirect_to release_items_path(id: @release_item.release_id), :notice  => "\"#{@release_item.title}\" has been updated!"
    else
      @affected_browsers_data = AffectedBrowsersData.find(:all, conditions: ["active = ?", true], order: "label ASC")
      @affected_designs_data = AffectedDesignsData.find(:all, conditions: ["active = ?", true], order: "label ASC")
      render 'edit'
    end
  end
  
  def destroy
    @release_item = ReleaseItem.find(params[:id])
    @release_item.destroy
    flash[:success] = "\"#{@release_item.title}\" has been deleted."
    redirect_to :back
  end
end

app/helpers/release_items_helper.rb
module ReleaseItemsHelper
  def count_or_zero
    self.any? ? self.count : 0
  end
	
  def build_source_url(source, ref)
    if source == "FogBugz"
      "<a href='https://clickmotive.fogbugz.com/default.asp?#{ref}' target='_blank'>#{ref}</a> - ".html_safe
    elsif source == "VersionOne"
      "<a href='https://www10.v1host.com/ClickMotive/Search.mvc/advanced?q=#{ref}' target='_blank'>#{ref}</a> - ".html_safe
    elsif source == "ZenDesk"
      "<a href='http://clickmotive.zendesk.com/tickets/#{ref}' target='_blank'>#{ref}</a> - ".html_safe
    end
  end
  
  def convert_risk_level_to_words(level)
    if level == "1" || level == 1.0
      "<span class='low-risk'>Low Risk</span>".html_safe
    elsif level == "2" || level == 2.0
      "<span class='medium-risk'>Medium Risk</span>".html_safe
    elsif level == "3" || level == 3.0
      "<span class='high-risk'>High Risk</span>".html_safe
    end
  end
  
  def convert_comfort_level_to_words(level)
    if level == "1" || level == 1.0
      "<span class='low-comfort'>Low Comfort</span>".html_safe
    elsif level == "2" || level == 2.0
      "<span class='medium-comfort'>Medium Comfort</span>".html_safe
    elsif level == "3" || level == 3.0
      "<span class='high-comfort'>High Comfort</span>".html_safe
    end
  end
end

app/views/release_items/_edit_form.html.erb
<script type="text/javascript">
	var checked = function checked(){
		$('input:checked').parent().addClass('checked');
		$('input:not(:checked)').parent().removeClass('checked');
	}
	
	var checkAll = function checkAll(section){
		$('label[data-category="' + section + '"]').find('input').each(function(){
			if($(this).is(':checked') || $(this).attr('checked') == false){
				$(this).prop('checked', false);
				checked();
			} else {
				$(this).prop('checked', true);
				checked();
			}
		});
	}
	
	$(window).load(function(){
		$('input[type="checkbox"]').click(function(){
			checked();
		});
		
		checked();
	});
</script>
<%= form_for(@release_item) do |f| %>
	<%= render 'shared/error_messages', :object => @release_item %>
	
	<%= f.label :item_type, "Type*" %>
	<%= f.select :item_type, options_for_select(["Data","General","Patch","Project","Upgrade"], selected: @release_item.item_type) %>
	<%= f.select :item_type, options_for_select(["Data","General","Patch","Project","Upgrade"], selected: @release_item.item_type) %>
	
	<%= f.label :source, "Source*" %>
	<%= f.select :source, options_for_select(["FogBugz","VersionOne","ZenDesk"], selected: @release_item.source) %>
	
	<%= f.label :source_reference, "Source Reference" %>
	<%= f.text_field :source_reference, placeholder: "Enter ID...", class: "input-medium" %>
	
	<%= f.label :title, "Title*" %>
	<%= f.text_field :title, placeholder: "Enter the release item title...", class: "input-xlarge" %>
	
	<%= f.label :is_data_change, "Data Change?*" %>
   	<label class="radio-btn"><%= f.radio_button :is_data_change, true %> yes &nbsp;</label>
   	<label class="radio-btn"><%= f.radio_button :is_data_change, false %> no</label>
	
	<%= f.label :is_config_change, "Config Change?*", class: "config-change" %>
   	<label class="radio-btn"><%= f.radio_button :is_config_change, true %> yes &nbsp;</label>
   	<label class="radio-btn"><%= f.radio_button :is_config_change, false %> no</label>
   	
   	<div class="release-item-affected-browsers">
	   	<h3>Affected Browsers?<h3>
	   	<div class="affected-browsers-list">
		   	<% for browser in @affected_browsers_data %>
		   		<label>
		   			<% if @release_item.affected_browsers.split(", ").collect(&:strip).include? browser.browser %>
			   			<%= check_box_tag "affected_browsers[]", browser.browser, true %> <%= browser.label %>
			   		<% else %>
			   			<%= check_box_tag "affected_browsers[]", browser.browser %> <%= browser.label %>
			   		<% end %>
			   	</label>
		   	<% end %>
			<div class="clearfix"></div>
	   	</div>
   	</div>
   	<div class="release-item-affected-designs">
	   	<h3>Affected Designs?</h3>
	   	<div class="affected-designs-list">
		   	<div class="affected-designs-list-heading">
		   		Acura (<span class="check-all" onclick="checkAll('Acura');">check/uncheck all</span>)
		   	</div>
		   	<% for design in @designs_acura %>
		   		<label data-category="<%= design.category %>">
		   			<% if @release_item.affected_designs.split(", ").collect(&:strip).include? design.design %>
			   			<%= check_box_tag "affected_designs[]", design.design, true %> <%= design.label %>
			   		<% else %>
			   			<%= check_box_tag "affected_designs[]", design.design %> <%= design.label %>
			   		<% end %>
			   	</label>
		   	<% end %>
		   	<div class="affected-designs-list-heading">
		   		Chevrolet (<span class="check-all" onclick="checkAll('Chevrolet');">check/uncheck all</span>)
		   	</div>
		   	<% for design in @designs_chevrolet %>
		   		<label data-category="<%= design.category %>">
		   			<% if @release_item.affected_designs.split(", ").collect(&:strip).include? design.design %>
			   			<%= check_box_tag "affected_designs[]", design.design, true %> <%= design.label %>
			   		<% else %>
			   			<%= check_box_tag "affected_designs[]", design.design %> <%= design.label %>
			   		<% end %>
			   	</label>
		   	<% end %>
		   	<div class="affected-designs-list-heading">
		   		General (<span class="check-all" onclick="checkAll('General');">check/uncheck all</span>)
		   	</div>
		   	<% for design in @designs_general %>
		   		<label data-category="<%= design.category %>">
		   			<% if @release_item.affected_designs.split(", ").collect(&:strip).include? design.design %>
			   			<%= check_box_tag "affected_designs[]", design.design, true %> <%= design.label %>
			   		<% else %>
			   			<%= check_box_tag "affected_designs[]", design.design %> <%= design.label %>
			   		<% end %>
			   	</label>
		   	<% end %>
		   	<div class="affected-designs-list-heading">
		   		GSM (<span class="check-all" onclick="checkAll('GSM');">check/uncheck all</span>)
		   	</div>
		   	<% for design in @designs_gsm %>
		   		<label data-category="<%= design.category %>">
		   			<% if @release_item.affected_designs.split(", ").collect(&:strip).include? design.design %>
			   			<%= check_box_tag "affected_designs[]", design.design, true %> <%= design.label %>
			   		<% else %>
			   			<%= check_box_tag "affected_designs[]", design.design %> <%= design.label %>
			   		<% end %>
			   	</label>
		   	<% end %>
		   	<div class="affected-designs-list-heading">
		   		Ford (<span class="check-all" onclick="checkAll('Ford');">check/uncheck all</span>)
		   	</div>
		   	<% for design in @designs_ford %>
		   		<label data-category="<%= design.category %>">
		   			<% if @release_item.affected_designs.split(", ").collect(&:strip).include? design.design %>
			   			<%= check_box_tag "affected_designs[]", design.design, true %> <%= design.label %>
			   		<% else %>
			   			<%= check_box_tag "affected_designs[]", design.design %> <%= design.label %>
			   		<% end %>
			   	</label>
		   	<% end %>
		   	<div class="affected-designs-list-heading">
		   		Mazda (<span class="check-all" onclick="checkAll('Mazda');">check/uncheck all</span>)
		   	</div>
		   	<% for design in @designs_mazda %>
		   		<label data-category="<%= design.category %>">
		   			<% if @release_item.affected_designs.split(", ").collect(&:strip).include? design.design %>
			   			<%= check_box_tag "affected_designs[]", design.design, true %> <%= design.label %>
			   		<% else %>
			   			<%= check_box_tag "affected_designs[]", design.design %> <%= design.label %>
			   		<% end %>
			   	</label>
		   	<% end %>
		   	<div class="affected-designs-list-heading">
		   		Scion (<span class="check-all" onclick="checkAll('Scion');">check/uncheck all</span>)
		   	</div>
		   	<% for design in @designs_scion %>
		   		<label data-category="<%= design.category %>">
		   			<% if @release_item.affected_designs.split(", ").collect(&:strip).include? design.design %>
			   			<%= check_box_tag "affected_designs[]", design.design, true %> <%= design.label %>
			   		<% else %>
			   			<%= check_box_tag "affected_designs[]", design.design %> <%= design.label %>
			   		<% end %>
			   	</label>
		   	<% end %>
		   	<div class="affected-designs-list-heading">
		   		Tools (<span class="check-all" onclick="checkAll('Tools');">check/uncheck all</span>)
		   	</div>
		   	<% for design in @designs_tools %>
		   		<label data-category="<%= design.category %>">
		   			<% if @release_item.affected_designs.split(", ").collect(&:strip).include? design.design %>
			   			<%= check_box_tag "affected_designs[]", design.design, true %> <%= design.label %>
			   		<% else %>
			   			<%= check_box_tag "affected_designs[]", design.design %> <%= design.label %>
			   		<% end %>
			   	</label>
		   	<% end %>
			<div class="clearfix"></div>
	   	</div>
   	</div>
	
	<%= f.label :affected_product, "Affected Product*" %>
	<%= f.select :affected_product, options_for_select(["N/A","Asset Server","Flex","Fusion Website","Inventory Process","New Relic"], selected: @release_item.affected_product) %>
	
	<%= f.label :level_of_risk, "Risk Level*" %>
	<%= f.select :level_of_risk, [["low",1],["medium",2],["high",3]], { include_blank: '' } %>
	
	<%= f.label :level_of_comfort, "Comfort Level*" %>
	<%= f.select :level_of_comfort, [["high",3],["medium",2],["low",1]], { include_blank: '' } %>
    
    <%= f.label :comments, "Comments" %>
	<%= f.text_field :comments, placeholder: "Enter comments for this item...", class: "input-xlarge" %>
    
    <%= f.hidden_field :modified_by, value: current_user.email %>
	
	<div class="form-action-buttons">
		<%= f.submit "Save", class: "btn btn-large btn-primary" %>
		<div class="btn-cancel">
			<%= link_to "Cancel", :back, class: "btn btn-large" %>
		</div>
	</div>
<% end %>

app/views/release_items/_release_items.html.erb
<article class="data">
	<div class="item-title">
		<%= build_source_url(item.source, item.source_reference) if item.source_reference? %><%= (item.is_data_change == true || item.is_config_change == true) ? "<span class='important-item'>#{item.title}</span>".html_safe : item.title %>
		<div class="item-title-actions">
			<% if user_signed_in? %>
				<%= link_to "Update", edit_release_item_path(item), class: "btn btn-small btn-primary" %>
				<%= link_to "Delete", item, method: :delete, data: { confirm: "Are you sure you want to delete #{item.title}?" }, class: "btn btn-small" %>
			<% end %>
		</div>
		<% if user_signed_in? && current_user.show_timestamps == true %>
			<%= "<div class='item-timestamp'>(last updated by #{item.name} on #{item.updated_at.strftime('%B %e, %Y @ %l:%M %P')})</div>".html_safe unless item.modified_by.blank? %>
		<% end %>
	</div>
	<div class="item-details">
		<span class="headings">Risk Level:</span> <%= convert_risk_level_to_words(item.level_of_risk) %><br />
		<span class="headings">Comfort Level:</span> <%= convert_comfort_level_to_words(item.level_of_comfort) %><br />
		<span class="headings">Data Change?</span> <%= item.is_data_change? ? "yes" : "no" %><br />
		<span class="headings">Config Change?</span> <%= item.is_config_change? ? "yes" : "no" %><br />
		<span class="headings">Affected Product:</span> <%= item.affected_product %><br />
		<span class="headings">Affected Browser(s):</span> <%= item.affected_browsers %><br />
		<span class="headings">Affected Design(s):</span> <%= item.affected_designs %><br />
		<div class="well">
			<span class="headings">Comments:</span> <%= item.comments %>
		</div>
	</div>
</article>

app/views/release_items/edit.html.erb
<% provide(:title, 'Update Release Item') %>

<h1>
	Update Release Item
</h1>

<%= render 'edit_form' %>

app/views/release_items/index.html.erb
<% provide(:title, "Release Items for: #{@release.title}") %>

<a name="top"></a>
<% if @release.archive == true %>
	<div class="label label-warning archive-tag">
		Archived
	</div>
<% end %>
<h1>
	Release Items for: <%= @release.title %><br />
	<%= link_to "View the Checklist for this Release", checklist_path(@release.id), class: "btn btn-small" %>
</h1>

<div class="release-details">
	<div class="left-column">
		<span class="headings">Primary Contact:</span> <%= (@release.contact != '') ? @release.contact : 'Unassigned' %><br />
		<span class="headings">Backup Contact:</span> <%= (@release.backup_contact != '') ? @release.backup_contact : 'Unassigned' %><br />
		<span class="headings">Risk Level:</span> <%= convert_risk_level_to_words(@release_items_levels_averages.risk_level_average) %><br />
		<span class="headings">Comfort Level:</span> <%= convert_comfort_level_to_words(@release_items_levels_averages.comfort_level_average) %><br />
		<span class="headings">Release Date:</span> <%= (@release.release_date) ? @release.release_date.strftime('%B %e, %Y') : 'Not Specified' %><br />
		<span class="headings">Code Cutoff Date:</span> <%= (@release.code_cutoff_date) ? @release.code_cutoff_date.strftime('%B %e, %Y') : 'Not Specified' %>
	</div>
	<div class="right-column">
		<span class="headings">Total Items in this Release:</span> <%= @release_items.count unless @release_items.nil? %><br />
		<span class="headings">Breakdown:</span> (Data: <%= @items_data.count unless @items_data.nil? %>, General: <%= @items_general.count unless @items_general.nil? %>, Patches: <%= @items_patch.count unless @items_patch.nil? %>, Projects: <%= @items_project.count unless @items_project.nil? %>, Upgrades: <%= @items_upgrade.count unless @items_upgrade.nil? %>)
	</div>
	<div class="clearfix"></div>
</div>

<div class="release-add-new-jump-to">
	<% if user_signed_in? %>
		<%= link_to "Add New Release Item", new_release_item_path(id: params[:id]), class: "btn btn-large btn-primary btn-new-release-item" %>
	<% end %>
	<div class="jump-to-item">
		<strong>Go Directly To:</strong> <%= link_to "General Items", "#GeneralItems" %> &nbsp;|&nbsp; <%= link_to "Project Items", "#ProjectItems" %> &nbsp;|&nbsp; <%= link_to "Upgrade Items", "#UpgradeItems" %> &nbsp;|&nbsp; <%= link_to "Data Items", "#DataItems" %> &nbsp;|&nbsp; <%= link_to "Patch Items", "#PatchItems" %>
	</div>
</div>

<a name="GeneralItems"></a>
<div class="release-items">
	<h3>
		General Items
	</h3>
	<span class="back-to-top">[<a href="#top">back to top</a>]</span>
	<section class="data-list">
		<% if @items_general.empty? %>
			<h2>There are no general items in this release.</h2>
		<% else %>
			<% @items_general.each do |item| %>
				<%= render 'release_items', item: item %>
			<% end %>
		<% end %>
	</section>
	<div class="clearfix"></div>
</div>
<a name="ProjectItems"></a>
<div class="release-items">
	<h3>
		Project Items
	</h3>
	<span class="back-to-top">[<a href="#top">back to top</a>]</span>
	<section class="data-list">
		<% if @items_project.empty? %>
			<h2>There are no projects in this release.</h2>
		<% else %>
			<% @items_project.each do |item| %>
				<%= render 'release_items', item: item %>
			<% end %>
		<% end %>
	</section>
	<div class="clearfix"></div>
</div>
<a name="UpgradeItems"></a>
<div class="release-items">
	<h3>
		Upgrade Items
	</h3>
	<span class="back-to-top">[<a href="#top">back to top</a>]</span>
	<section class="data-list">
		<% if @items_upgrade.empty? %>
			<h2>There are no upgrade items in this release.</h2>
		<% else %>
			<% @items_upgrade.each do |item| %>
				<%= render 'release_items', item: item %>
			<% end %>
		<% end %>
	</section>
	<div class="clearfix"></div>
</div>
<a name="DataItems"></a>
<div class="release-items">
	<h3>
		Data Items
	</h3>
	<span class="back-to-top">[<a href="#top">back to top</a>]</span>
	<section class="data-list">
		<% if @items_data.empty? %>
			<h2>There are no data items in this release.</h2>
		<% else %>
			<% @items_data.each do |item| %>
				<%= render 'release_items', item: item %>
			<% end %>
		<% end %>
	</section>
	<div class="clearfix"></div>
</div>
<a name="PatchItems"></a>
<div class="release-items">
	<h3>
		Patch Items
	</h3>
	<span class="back-to-top">[<a href="#top">back to top</a>]</span>
	<section class="data-list">
		<% if @items_patch.empty? %>
			<h2>There are no patches in this release.</h2>
		<% else %>
			<% @items_patch.each do |item| %>
				<%= render 'release_items', item: item %>
			<% end %>
		<% end %>
	</section>
	<div class="clearfix"></div>
</div>

<% if user_signed_in? %>
	<%= link_to "Add New Release Item", new_release_item_path(id: params[:id]), class: "btn btn-large btn-primary btn-new-release-item" %>
<% end %>

app/views/release_items/new.html.erb
<% provide(:title, 'Create New Release Item') %>

<h1>
	Create New Release Item
</h1>

<%= render 'new_form' %>