config/routes.rb
QaHub::Application.routes.draw do
  devise_for :users, path_names: { sign_up: 'register', sign_in: 'sign-in', sign_out: 'sign-out' }
  
  root to: 'static_pages#home'
  
  resources :releases
  
  resources :checklists do
  	get 'toggle_tool', on: :member
  	get 'toggle_item', on: :member
  	get 'toggle_applicable', on: :member
  end
  
  resources :release_items
  
  resources :comments
end

app/controllers/checklists_controller.rb
class ChecklistsController < ApplicationController
  before_filter :authenticate_user!, except: [:show]
  
  def show
    @release = Release.find(params[:id])
    @checklist_tools = ChecklistTool.find(:all, joins: :release_data, conditions: ["checklist_tools.release_id = ?", params[:id]], order: "checklist_tools.release_data_id ASC")
    @checklist_development_items = ChecklistItem.find(:all, select: "checklist_items.*, users.id as uid, users.email, users.name", joins: [:release_data, "LEFT JOIN comments ON comments.checklist_item_id = checklist_items.id", "LEFT JOIN users ON users.email = checklist_items.modified_by"], conditions: ["checklist_items.release_id = ? AND release_data.section = ?", params[:id], "development"], group: "checklist_items.id, uid", order: "checklist_items.id ASC")
    @checklist_stage_items = ChecklistItem.find(:all, select: "checklist_items.*, users.id as uid, users.email, users.name", joins: [:release_data, "LEFT JOIN comments ON comments.checklist_item_id = checklist_items.id", "LEFT JOIN users ON users.email = checklist_items.modified_by"], conditions: ["checklist_items.release_id = ? AND release_data.section = ?", params[:id], "stage"], group: "checklist_items.id, uid", order: "checklist_items.id ASC")
    @checklist_production_items = ChecklistItem.find(:all, select: "checklist_items.*, users.id as uid, users.email, users.name", joins: [:release_data, "LEFT JOIN comments ON comments.checklist_item_id = checklist_items.id", "LEFT JOIN users ON users.email = checklist_items.modified_by"], conditions: ["checklist_items.release_id = ? AND release_data.section = ?", params[:id], "production"], group: "checklist_items.id, uid", order: "checklist_items.id ASC")
    @projects = ReleaseItem.find(:all, select: "release_items.*, users.email, users.name", joins: "LEFT JOIN users ON users.email = release_items.modified_by", conditions: ["release_items.item_type = ? AND release_items.release_id = ?", 'Project', params[:id]])
    @project_comments = Comment.find(:all, conditions: ["release_id = ? AND checklist_item_type = ?", params[:id], 'Project'])
  end
  
  def toggle_tool
    @tool = ChecklistTool.find(params[:id])
    @tool.toggle!(:value)
    @tool.update_column(:modified_by, current_user.email)
    respond_to do |format|
      format.js
	  end
  end
  
  def toggle_item
    @item = ChecklistItem.find(params[:id])
    @item.toggle!(:value)
    @item.update_column(:modified_by, current_user.email)
    render nothing: true
  end
  
  def toggle_applicable
    @item = ChecklistItem.find(params[:id])
    @item.toggle!(:applicable)
    @item.update_column(:modified_by, current_user.email)
    respond_to do |format|
      format.js
	  end
  end
  
  def destroy
    @checklist_item = ChecklistItem.find(params[:id])
    @checklist_item.destroy
  end
end

app/helpers/checklists_helper.rb
module ChecklistsHelper
	def toggle_tool_image(tool)
	  tool.value? ? "<img src='/assets/#{tool.release_data.label}_true.png' alt='#{tool.release_data.label}' />".html_safe : "<img src='/assets/#{tool.release_data.label}_false.png' alt='#{tool.release_data.label}' />".html_safe
	end
	
	def toggle_item_checkbox(item)
	  @environment = "'#{item.environment}'"
	  if user_signed_in?
      @disabled = ""
	  else
	    @disabled = "disabled='disabled'"
	  end
	  
		if item.value == true
		  if item.applicable == true
		    "<input type='checkbox' id='checklist_item_#{item.id}' data-id='#{item.id}' onclick=\"toggleItemCheckbox(#{item.id},#{@environment})\" checked='checked' #{@disabled} /> #{item.release_data.label}".html_safe
		  elsif item.applicable == false
		    "<input type='checkbox' id='checklist_item_#{item.id}' data-id='#{item.id}' onclick=\"toggleItemCheckbox(#{item.id},#{@environment})\" checked='checked' disabled='disabled' /> #{item.release_data.label}".html_safe
		  end
    elsif item.value == false
		  if item.applicable == true
		    "<input type='checkbox' id='checklist_item_#{item.id}' data-id='#{item.id}' onclick=\"toggleItemCheckbox(#{item.id},#{@environment})\" #{@disabled} /> #{item.release_data.label}".html_safe
		  elsif item.applicable == false
		    "<input type='checkbox' id='checklist_item_#{item.id}' data-id='#{item.id}' onclick=\"toggleItemCheckbox(#{item.id},#{@environment})\" disabled='disabled' /> #{item.release_data.label}".html_safe
		  end
	  end
	end
	
	def toggle_applicable(item)
		item.applicable? ? "<img src='/assets/iconNotApplicable.png' alt='Not Applicable' /> Mark Not Applicable".html_safe : "<img src='/assets/iconSave.png' alt='Applicable' /> Mark Applicable".html_safe
	end
end

app/views/checklists/show.html.erb
<% provide(:title, "Checklist for: #{@release.title}") %>
<script type="text/javascript">
	$(document).ready(function() {
		$(".fancybox").fancybox({
			padding: 20,
			scrolling: 'no',
			maxWidth: 700,
			afterClose: function() { parent.location.reload(true); }
		});
	});
</script>

<% if @release.archive == true %>
	<div class="label label-warning archive-tag">
		Archived
	</div>
<% end %>
<h1>
	Checklist for: <%= @release.title %><br />
	<%= link_to "View the Release List for this Release", release_items_path(id: @release.id), class: "btn btn-small" %>
</h1>

<div class="checklist-release-details">
	<span class="headings">Primary Contact:</span> <%= (@release.contact != '') ? @release.contact : 'Unassigned' %><br />
	<span class="headings">Backup Contact:</span> <%= (@release.backup_contact != '') ? @release.backup_contact : 'Unassigned' %><br />
	<span class="headings">Release Date:</span> <%= (@release.release_date) ? @release.release_date.strftime('%B %e, %Y') : 'Not Specified' %><br />
	<span class="headings">Code Cutoff Date:</span> <%= (@release.code_cutoff_date) ? @release.code_cutoff_date.strftime('%B %e, %Y') : 'Not Specified' %>
</div>
<div class="checklist-affected-tools">
	<h3>
		Affected Tools
	</h3>
	<% @checklist_tools.each do |tool| %>
		<div class="tool">
			<% if user_signed_in? %>
				<%= link_to toggle_tool_image(tool), toggle_tool_checklist_path(tool), remote: true, id: "checklist_tool_#{tool.id}" %>
			<% else %>
				<%= toggle_tool_image(tool) %>
			<% end %>
		</div>
	<% end %>
</div>
<div class="checklist-development">
	<h3>
		Development Branch
		<% if user_signed_in? %>
			<span class="status"></span>
		<% end %>
	</h3>
	<% @checklist_development_items.each do |item| %>
		<div class="checklist-row">
			<label for="checklist_item_<%= item.id %>" <%= "class=strikethrough" if item.applicable == false %>>
				<%= toggle_item_checkbox(item) %>
				<% if user_signed_in? && current_user.show_timestamps == true %>
					<%= "<span class='item-timestamp'>(last updated by #{item.name} on #{item.updated_at.strftime('%B %e, %Y @ %l:%M %P')})</span>".html_safe unless item.modified_by.blank? %>
				<% end %>
			</label>
			<div class="clearfix"></div>
			<% if user_signed_in? %>
				<div class="actions">
					<%= link_to toggle_applicable(item), toggle_applicable_checklist_path(item), remote: true, id: "checklist_item_applicable_#{item.id}" %>
					&nbsp; <strong>|</strong> &nbsp;
					<%= link_to "<img src='/assets/iconAdd.png' alt='Add a Comment' /> Add a Comment".html_safe, new_comment_path(release_id: @release.id, checklist_item_id: item.id, checklist_item_type: 'Item'), class: "fancybox", data: { fancybox_type: "iframe" } %>
				</div>
				<div class="clearfix"></div>
			<% end %>
			<div class="comments">
				<% item.comments.each do |c| %>
					<% if c.checklist_item_type == 'Item' %>
						<div class="comment well">
							<div class="heading">
								<%= c.author %> said on <%= c.updated_at.strftime('%B %e, %Y @ %l:%M %P') %>
								<% if user_signed_in? %>
									&nbsp;|&nbsp;
									<%= link_to image_tag('/assets/iconEdit.png'), edit_comment_path(c.id), class: "fancybox", data: { fancybox_type: "iframe" } %>
									<%= link_to image_tag('/assets/iconDelete.png'), c, method: :delete, data: { confirm: "Are you sure you want to delete this comment?" } %>
								<% end %>
							</div>
							<%= c.comment.html_safe %>
						</div>
					<% end %>
				<% end %>
			</div>
			<div class="clearfix"></div>
		</div>
	<% end %>
</div>
<div class="checklist-stage">
	<h3>
		Stage Branch
		<% if user_signed_in? %>
			<span class="status"></span>
		<% end %>
	</h3>
	<% @checklist_stage_items.each do |item| %>
		<div class="checklist-row">
			<label for="checklist_item_<%= item.id %>" <%= "class=strikethrough" if item.applicable == false %>>
				<%= toggle_item_checkbox(item) %>
				<% if user_signed_in? && current_user.show_timestamps == true %>
					<%= "<span class='item-timestamp'>(last updated by #{item.name} on #{item.updated_at.strftime('%B %e, %Y @ %l:%M %P')})</span>".html_safe unless item.modified_by.blank? %>
				<% end %>
			</label>
			<div class="clearfix"></div>
			<% if user_signed_in? %>
				<div class="actions">
					<%= link_to toggle_applicable(item), toggle_applicable_checklist_path(item), remote: true, id: "checklist_item_applicable_#{item.id}" %>
					&nbsp; <strong>|</strong> &nbsp;
					<%= link_to "<img src='/assets/iconAdd.png' alt='Add a Comment' /> Add a Comment".html_safe, new_comment_path(release_id: @release.id, checklist_item_id: item.id, checklist_item_type: 'Item'), class: "fancybox", data: { fancybox_type: "iframe" } %>
				</div>
				<div class="clearfix"></div>
			<% end %>
			<div class="comments">
				<% item.comments.each do |c| %>
					<% if c.checklist_item_type == 'Item' %>
						<div class="comment well">
							<div class="heading">
								<%= c.author %> said on <%= c.updated_at.strftime('%B %e, %Y @ %l:%M %P') %>
								<% if user_signed_in? %>
									&nbsp;|&nbsp;
									<%= link_to image_tag('/assets/iconEdit.png'), edit_comment_path(c.id), class: "fancybox", data: { fancybox_type: "iframe" } %>
									<%= link_to image_tag('/assets/iconDelete.png'), c, method: :delete, data: { confirm: "Are you sure you want to delete this comment?" } %>
								<% end %>
							</div>
							<%= c.comment.html_safe %>
						</div>
					<% end %>
				<% end %>
			</div>
			<div class="clearfix"></div>
		</div>
	<% end %>
</div>
<div class="checklist-production">
	<h3>
		Production Branch
		<% if user_signed_in? %>
			<span class="status"></span>
		<% end %>
	</h3>
	<% @checklist_production_items.each do |item| %>
		<div class="checklist-row">
			<label for="checklist_item_<%= item.id %>" <%= "class=strikethrough" if item.applicable == false %>>
				<%= toggle_item_checkbox(item) %>
				<% if user_signed_in? && current_user.show_timestamps == true %>
					<%= "<span class='item-timestamp'>(last updated by #{item.name} on #{item.updated_at.strftime('%B %e, %Y @ %l:%M %P')})</span>".html_safe unless item.modified_by.blank? %>
				<% end %>
			</label>
			<div class="clearfix"></div>
			<% if user_signed_in? %>
				<div class="actions">
					<%= link_to toggle_applicable(item), toggle_applicable_checklist_path(item), remote: true, id: "checklist_item_applicable_#{item.id}" %>
					&nbsp; <strong>|</strong> &nbsp;
					<%= link_to "<img src='/assets/iconAdd.png' alt='Add a Comment' /> Add a Comment".html_safe, new_comment_path(release_id: @release.id, checklist_item_id: item.id, checklist_item_type: 'Item'), class: "fancybox", data: { fancybox_type: "iframe" } %>
				</div>
				<div class="clearfix"></div>
			<% end %>
			<div class="comments">
				<% item.comments.each do |c| %>
					<% if c.checklist_item_type == 'Item' %>
						<div class="comment well">
							<div class="heading">
								<%= c.author %> said on <%= c.updated_at.strftime('%B %e, %Y @ %l:%M %P') %>
								<% if user_signed_in? %>
									&nbsp;|&nbsp;
									<%= link_to image_tag('/assets/iconEdit.png'), edit_comment_path(c.id), class: "fancybox", data: { fancybox_type: "iframe" } %>
									<%= link_to image_tag('/assets/iconDelete.png'), c, method: :delete, data: { confirm: "Are you sure you want to delete this comment?" } %>
								<% end %>
							</div>
							<%= c.comment.html_safe %>
						</div>
					<% end %>
				<% end %>
			</div>
			<div class="clearfix"></div>
		</div>
	<% end %>
</div>
<div class="checklist-projects">
	<h3>
		Release Projects
	</h3>
	<% if @projects.empty? %>
		<h2>There are no projects in this release.</h2>
	<% else %>
		<% @projects.each do |project| %>
			<div class="checklist-row">
				<label for="checklist_item_<%= project.id %>">
					<%= project.title %>
					<% if user_signed_in? && current_user.show_timestamps == true %>
						<%= "<span class='item-timestamp'>(last updated by #{project.name} on #{project.updated_at.strftime('%B %e, %Y @ %l:%M %P')})</span>".html_safe %>
					<% end %>
				</label>
				<div class="clearfix"></div>
				<% if user_signed_in? %>
					<div class="actions">
						<%= link_to "<img src='/assets/iconAdd.png' alt='Add a Comment' /> Add a Comment".html_safe, new_comment_path(release_id: @release.id, checklist_item_id: project.id, checklist_item_type: 'Project'), class: "fancybox", data: { fancybox_type: "iframe" } %>
					</div>
					<div class="clearfix"></div>
				<% end %>
				<div class="comments">
					<% @project_comments.each do |c| %>
						<% if c.checklist_item_id == project.id %>
							<div class="comment well">
								<div class="heading">
									<%= c.author %> said on <%= c.updated_at.strftime('%B %e, %Y @ %l:%M %P') %> &nbsp;|&nbsp;
									<% if user_signed_in? %>
										<%= link_to image_tag('/assets/iconEdit.png'), edit_comment_path(c.id), class: "fancybox", data: { fancybox_type: "iframe" } %>
										<%= link_to image_tag('/assets/iconDelete.png'), c, method: :delete, data: { confirm: "Are you sure you want to delete this comment?" } %>
									<% end %>
								</div>
								<%= c.comment.html_safe %>
							</div>
						<% end %>
					<% end %>
				</div>
				<div class="clearfix"></div>
			</div>
		<% end %>
	<% end %>
</div>
<div class="clearfix"></div>

app/views/checklists/toggle_applicable.js.erb
$("#checklist_item_applicable_<%= @item.id %>").parent().parent().fadeOut(250, function(){
	if(<%= @item.applicable %> == false){
		$("label[for='checklist_item_<%= @item.id %>']").addClass("strikethrough").find("input").attr("disabled","disabled");
		$(this).find("#checklist_item_applicable_<%= @item.id %>").html("<%= toggle_applicable(@item) %>");
		$(this).fadeIn(250);
	}else if(<%= @item.applicable %> == true){
		$("label[for='checklist_item_<%= @item.id %>']").removeClass("strikethrough").find("input").removeAttr("disabled");
		$(this).find("#checklist_item_applicable_<%= @item.id %>").html("<%= toggle_applicable(@item) %>");
		$(this).fadeIn(250);
	}
});

app/views/checklists/toggle_tool.js.erb
$("#checklist_tool_<%= @tool.id %>").fadeOut(250, function(){
	$(this).html("<%= toggle_tool_image(@tool) %>").fadeIn(250);
});