config/routes.rb
QaHub::Application.routes.draw do
  devise_for :users, path_names: { sign_up: 'register', sign_in: 'sign-in', sign_out: 'sign-out' }
  
  root to: 'static_pages#home'
  
  resources :releases
  
  resources :checklists do
  	get 'toggle_tool', on: :member
  	get 'toggle_item', on: :member
  	get 'toggle_applicable', on: :member
  end
  
  resources :release_items
  
  resources :comments
end

app/views/layouts/_application_head.html.erb
<title><%= full_title(yield(:title)) %></title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<%= stylesheet_link_tag    "application", media: "all" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>

app/views/layouts/_footer.html.erb
<footer class="footer">
	&copy; 2013 Copyright <%= link_to "QA Hub", root_path %> | All Rights Reserved
	<%= debug(params) if Rails.env.development? %>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "QA Hub", root_path, id: "logo" %>
			<nav>
				<ul class="nav pull-right">
					<li class="top-level <%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li>
					<li class="top-level <%= 'active' if current_page?(releases_path) %>"><%= link_to "Releases", releases_path %></li>
					<li id="fat-menu" class="dropdown">
						<% if signed_in? %>
							<a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= "#{current_user.name}" %> <b class="caret"></b></a>
						<% else %>
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin <b class="caret"></b></a>
						<% end %>
						<ul class="dropdown-menu">
							<% if signed_in? %>
								<li><%= link_to "QA Confluence Page", "http://confluence.clickmotive.com/display/qa/Home", target: "_blank" %></li>
				                <li class="divider"></li>
								<li><%= link_to "Profile", edit_user_registration_path %></li>
				                <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
			    	        <% else %>
			    	        	<li><%= link_to "Sign In", new_user_session_path %></li>
			    	        <% end %>
			            </ul>
					</li>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<%= render 'layouts/application_head' %>  
		<%= render 'layouts/shim' %>    
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container-wrapper">
			<div class="container">
				<% flash.each do |key, value| %>
					<%= content_tag(:div, value, class: "alert alert-#{key}") %>
				<% end %>
				<%= yield %>
				<%= render 'layouts/footer' %>
			</div>
		</div>
	</body>
</html>

app/views/layouts/application_blank.html.erb
<!DOCTYPE html>
<html>
	<head>
		<%= render 'layouts/application_head' %>
		<%= render 'layouts/shim' %>    
	</head>
	<body>
		<%= yield %>
	</body>
</html>

app/views/layouts/application_frame.html.erb
<!DOCTYPE html>
<html>
	<head>
		<%= render 'layouts/application_head' %>
		<%= render 'layouts/shim' %>    
	</head>
	<body class="body-frame">
		<div class="frame-container">
			<%= yield %>
		</div>
	</body>
</html>